version: '3.8'

services:
  # Base de datos PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: sanguapp_db
    environment:
      POSTGRES_DB: sanguapp
      POSTGRES_USER: sanguapp
      POSTGRES_PASSWORD: sanguapp_secure_2024
      POSTGRES_INITDB_ARGS: '--encoding=UTF8 --locale=C'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"
    networks:
      - sanguapp_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sanguapp"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API (Node.js + Express)
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: sanguapp_api
    environment:
      NODE_ENV: production
      PORT: 3001
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: sanguapp
      DB_USER: sanguapp
      DB_PASSWORD: sanguapp_secure_2024
      JWT_SECRET: sanguapp_jwt_super_secret_key_2024_secure
      JWT_EXPIRES_IN: 7d
      CORS_ORIGIN: http://localhost:3000,http://localhost:80
      API_RATE_LIMIT: 100
    volumes:
      - ./backend/uploads:/app/uploads
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - sanguapp_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend React App
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: http://localhost:3001/api
        REACT_APP_APP_NAME: SanguApp
        REACT_APP_VERSION: 1.0.0
    container_name: sanguapp_web
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - sanguapp_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx Proxy (para producción con SSL)
  nginx:
    image: nginx:alpine
    container_name: sanguapp_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
    networks:
      - sanguapp_network
    restart: unless-stopped
    profiles:
      - production

  # Herramienta de administración DB (opcional)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: sanguapp_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@sanguapp.com
      PGADMIN_DEFAULT_PASSWORD: admin2024
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - sanguapp_network
    restart: unless-stopped
    profiles:
      - dev

volumes:
  postgres_data:
    driver: local

networks:
  sanguapp_network:
    driver: bridge
